[package]
name = 'rbm25'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rbm25'

[dependencies]
bm25 = { version = "0.3.1", features = ["language_detection"] }
extendr-api = '*'
