# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rbm25_wrappers", use_symbols = TRUE, package_name = "rbm25")

#' @usage NULL
#' @useDynLib rbm25, .registration = TRUE
NULL

build_engine <- function(corpus, language, k1, b) .Call(wrap__build_engine, corpus, language, k1, b)

search <- function(engine, query, max_n) .Call(wrap__search, engine, query, max_n)


# nolint end
